/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `/components/Button`; params?: Router.UnknownInputParams; } | { pathname: `/components/Input`; params?: Router.UnknownInputParams; } | { pathname: `/components/styles/inputstyles`; params?: Router.UnknownInputParams; } | { pathname: `/components/styles/buttonstyles`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/new` | `/new`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/relatorios` | `/relatorios`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/talhoes` | `/talhoes`; params?: Router.UnknownInputParams; } | { pathname: `/components/Header`; params?: Router.UnknownInputParams; } | { pathname: `/components/Header/style`; params?: Router.UnknownInputParams; } | { pathname: `/components/Pill`; params?: Router.UnknownInputParams; } | { pathname: `/components/Pill/styles`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Button`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Input`; params?: Router.UnknownOutputParams; } | { pathname: `/components/styles/inputstyles`; params?: Router.UnknownOutputParams; } | { pathname: `/components/styles/buttonstyles`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/new` | `/new`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/relatorios` | `/relatorios`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/talhoes` | `/talhoes`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Header`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Header/style`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Pill`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Pill/styles`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/components/Button${`?${string}` | `#${string}` | ''}` | `/components/Input${`?${string}` | `#${string}` | ''}` | `/components/styles/inputstyles${`?${string}` | `#${string}` | ''}` | `/components/styles/buttonstyles${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/new${`?${string}` | `#${string}` | ''}` | `/new${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/relatorios${`?${string}` | `#${string}` | ''}` | `/relatorios${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/talhoes${`?${string}` | `#${string}` | ''}` | `/talhoes${`?${string}` | `#${string}` | ''}` | `/components/Header${`?${string}` | `#${string}` | ''}` | `/components/Header/style${`?${string}` | `#${string}` | ''}` | `/components/Pill${`?${string}` | `#${string}` | ''}` | `/components/Pill/styles${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `/components/Button`; params?: Router.UnknownInputParams; } | { pathname: `/components/Input`; params?: Router.UnknownInputParams; } | { pathname: `/components/styles/inputstyles`; params?: Router.UnknownInputParams; } | { pathname: `/components/styles/buttonstyles`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/new` | `/new`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/relatorios` | `/relatorios`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/talhoes` | `/talhoes`; params?: Router.UnknownInputParams; } | { pathname: `/components/Header`; params?: Router.UnknownInputParams; } | { pathname: `/components/Header/style`; params?: Router.UnknownInputParams; } | { pathname: `/components/Pill`; params?: Router.UnknownInputParams; } | { pathname: `/components/Pill/styles`; params?: Router.UnknownInputParams; };
    }
  }
}
